name: test

on:
  push:
    branches:
      - main
    paths:
      - plugins/*
      - README.md

jobs:
  all_plugins:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
        with:
          fetch-depth: 0

      - name: Test all plugins pass our requirements
        run: bash scripts/test_plugin.bash --all
